### ISSUE TITLE
Does this support Django 1.4?

### ISSUE THREAD

**Issue by prologic** [akanouras/django-pudb#1]
Hi, I'm getting an error using this middleware:

```
[05/Dec/2014 11:41:11] "GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib64/python2.6/wsgiref/handlers.py", line 93, in run
    self.result = application(self.environ, self.start_response)
  File "/home/vagrant/.virtualenvs/django-upgrade/lib/python2.6/site-packages/django/contrib/staticfiles/handlers.py", line 67, in __call__
    return self.application(environ, start_response)
  File "/home/vagrant/.virtualenvs/django-upgrade/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 241, in __call__
    response = self.get_response(request)
  File "/home/vagrant/.virtualenvs/django-upgrade/lib/python2.6/site-packages/django/core/handlers/base.py", line 177, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/vagrant/.virtualenvs/django-upgrade/lib/python2.6/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/checkout/code/apncore/cache/decorators/__init__.py", line 64, in patched_view
    response = viewfunc(request, *args, **kwargs)
  File "/home/vagrant/checkout/code/finda/sitedetail/views.py", line 35, in favicon
    return serve(request, path=favicon_path, storage=FAVICON_STORAGE, stream=False)
  File "/home/vagrant/checkout/code/apncore/storage/views/static.py", line 54, in serve
    file_info = storage.fs.getinfo(fullpath)
  File "/home/vagrant/checkout/code/apncore/util/functional.py", line 10, in inner
    self._setup_once()
  File "/home/vagrant/checkout/code/apncore/util/functional.py", line 54, in _setup_once
    self._setup()
  File "/home/vagrant/checkout/code/apncore/storage/backends/media.py", line 54, in _setup
    if cache_fs in uncached_media_fs.writefs:
  File "/home/vagrant/checkout/code/apncore/util/functional.py", line 10, in inner
    self._setup_once()
  File "/home/vagrant/checkout/code/apncore/util/functional.py", line 54, in _setup_once
    self._setup()
  File "/home/vagrant/checkout/code/apncore/storage/backends/media.py", line 43, in _setup
    media_fs = layeredfs.make_layered_fs(write_fs_string, *read_fs_strings)
  File "/home/vagrant/checkout/code/apncore/storage/layeredfs.py", line 33, in make_layered_fs
    multi_fs.addfs(**kwargs)
  File "/home/vagrant/.virtualenvs/django-upgrade/lib/python2.6/site-packages/fs/base.py", line 146, in acquire_lock
    return func(self, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/django-upgrade/lib/python2.6/site-packages/fs/multifs.py", line 151, in addfs
    self.fs_priorities[name] = priority
AttributeError: 'MultiFS' object has no attribute 'fs_priorities'
```

**Comment by prologic** [comment]
My configuration is as follows:

```
# ===========
# django-pudb
# ===========

try:
    import django_pudb  # noqa
    HAS_DJANGO_PUDB = True
except ImportError:
    HAS_DJANGO_PUDB = False

if HAS_DJANGO_PUDB:
    MIDDLEWARE_CLASSES += ("django_pudb.PudbMiddleware",)
    DEBUG_PROPAGATE_EXCEPTIONS = True
```
