### ISSUE TITLE
Python 2.7 no longer supported in it

### ISSUE THREAD

**Issue by umarmughal824** [akanouras/django-pudb#3]
If I use it for Python 2.7 it gives me that error

> Unhandled exception in thread started by <function wrapper at 0x7fce75cb1140>
Traceback (most recent call last):
  File "/home/umar/django-logging-advance-env2/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/umar/django-logging-advance-env2/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/umar/django-logging-advance-env2/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/umar/django-logging-advance-env2/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/umar/django-logging-advance-env2/local/lib/python2.7/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/umar/django-logging-advance-env2/local/lib/python2.7/site-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python2.7/logging/config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python2.7/logging/config.py", line 551, in configure
    'formatter %r: %s' % (name, e))
ValueError: Unable to configure formatter 'django.server': __init__() got an unexpected keyword argument 'style'

**Comment by umarmughal824** [comment]
This is python version details

> Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.

**Comment by umarmughal824** [comment]
I guess its related to the Pull Request. I'm also using Django 1.10.
